# Generated by Django 4.2.6 on 2023-10-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bss_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('employee_name', models.CharField(editable=False, max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
            ],
        ),
    ]
